### ISSUE TITLE
Add component for RTL mode enabling/disabling

### ISSUE THREAD

**Issue by owlet1997** [jmix-projects/front-demo-r2#1]
Toggle button could be used like this:
![image](https://user-images.githubusercontent.com/45730069/141735463-36866134-00fa-4a3c-8878-90ed4c7b2b9d.png)

Component should be placed in the settings block:
![image](https://user-images.githubusercontent.com/45730069/141735163-701c888c-bd0f-4d02-9d14-d0157dabedfd.png)

**Comment by web-devel** [comment]
Locale with RTL support has been added:
![image](https://user-images.githubusercontent.com/3295727/141742375-bc90ee3f-fdcc-4027-afe5-e1ca89c04dd0.png)
