### ISSUE TITLE
Create custom themes

### ISSUE THREAD

**Issue by owlet1997** [jmix-projects/front-demo-r2#2]
1. Custom size theme
Name of theme: Big size
It is not necessary to override all default values, font size and some element sizes (buttons e.g.) should be bigger than default sizes

2. Custom colour theme
Name of theme: Custom theme
It is not necessary to override all default values, just create some differences with existing light theme

**Comment by web-devel** [comment]
The size preset is placed in a separate combobox. Preset is called `Large` (instead of big).
![image](https://user-images.githubusercontent.com/3295727/141799896-75b80c7d-7fd1-4d16-8127-67d6ced5d43d.png)

**Comment by owlet1997** [comment]
please change background colour of Header in the Custom theme
