### ISSUE TITLE
Add new locales 

### ISSUE THREAD

**Issue by owlet1997** [jmix-projects/front-demo-r2#6]
- [x] using attached npm package [locale.zip](https://github.com/jmix-projects/front-demo-r2/files/7545752/locale.zip)
- [x] create new handcrafted locale

**Comment by web-devel** [comment]
Package (source and dist) with cn locale is placed in the `front-cn-locale-example-package` directory.
It's installed in the frontend app as external dependency: `    "jmix-i18n-cn": "file:../front-cn-locale-example-package",`
