### ISSUE TITLE
Add screen (or several screens) with visual components

### ISSUE THREAD

**Issue by owlet1997** [jmix-projects/front-demo-r2#7]
Not all of them are implemented yet, here is the epic [issue](https://github.com/Haulmont/jmix-frontend/issues/25)
Use components from `@haulmont/jmix-react-antd` library:
- [x] `<Grid>`
- [x] `<Header>` 
- [x] `<Footer>`
- [x] `<Drawer>`  (Sidebar)
- [x] `<TabSheet>`
- [x] `<Card>`
- [x] `<Label>` 
- [x] `<Table>` (DataTable)
- [x] `<Tree>`
- [x] `<Calendar>`
- [x] `<Image>`
- [x] `<ProgressBar>`
- [x] `<Tooltip>`
- [x] `<TextField>`
- [x] `<TextArea>`
- [x] `<DateField>` 
- [x] `<TimeField>`
- [x] `<Select> `
- [x] `<CheckBox>`
- [x] `<RadioButton>`
- [x] `<Button>`
- [x] `<Slider>` 
- [x] `<ColorPicker>`
- [x] `<FileUpload>`
- [x] `<MaskedField>`
- [x] `<Pagination>`
- [x] `<SourceCodeEditor>`
- [x] `<RichTextArea>`
- [x] `<Form>`
- [x] `<Filter>`
- [x] `<EntityPicker>`
- [x] `<Icons>`

**Comment by web-devel** [comment]
Waiting for the fix: Haulmont/jmix-frontend/issues/888
